version: 2.1
jobs:
  build:
    docker:
     - image: thirupathip/devops
    working_directory: ~/home
    steps:
      - checkout
      - run: 
          name: sample
          command: |
            mkdir project
            cd project
      - run:
          name: dir
          command: |
             ls
             bash wel.sh
